apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
  namespace: fcg-apps
  labels:
    app: notifications-api
stringData:
  # Placeholders for sensitive configuration values
  # RabbitMQ credentials
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"